# https://travis-ci.org/jazzband/django-push-notifications
sudo: false
language: python
python: "3.7"
dist: xenial

env:
  - TOXENV=py27-django111
  - TOXENV=py37-django111
  - TOXENV=py37-django20
  - TOXENV=py37-django22
  - TOXENV=flake8

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_failure: always
    on_success: change

deploy:
  provider: pypi
  user: jazzband
  server: https://jazzband.co/projects/django-push-notifications/upload
  distributions: sdist bdist_wheel
  password:
    secure: WIP
  on:
    tags: true
    repo: jazzband/django-push-notifications

